version: '3'
services:
  web:
    build: .
    container_name: franks-calendar-web
    environment:
      FLASK_ENV: development
      CALENDAR_LINK: https://calendar.google.com/calendar/ical/ocrlnk9gfl2ee4shh46ffd2kgk%40group.calendar.google.com/private-50a283aa50d5e2b1108d41806b087c44/basic.ics
      ADMIN_CODE: ${ADMIN_CODE}
      MONGODB_SRV: ${MONGODB_SRV}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
    env_file:
      - ./.env
    restart: always
    tty: true
    ports:
    - "5000:5000"
    volumes:
    - ".:/www"
